FROM tomcat:8-jre7
MAINTAINER Emilio J. Alarcon <ejalarcon@gmail.com>
ENV CATALINA_BASE /usr/local/tomcat
COPY tomcat-users.xml $CATALINA_BASE/conf/tomcat-users.xml
COPY qpri_mult_web_gestionempleadosweb_01.war $CATALINA_BASE/webapps/qpri_mult_web_gestionempleadosweb_01.war

